resource containerAppEnvironment 'Microsoft.Web/kubeEnvironments@2022-09-01' = {
  name: containerAppEnvName
  location: containerAppEnvLocation 
  kind: 'containerenvironment'
  properties: {
    environmentType: 'managed'
    internalLoadBalancerEnabled: false
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
  }
}